/* model.h - int8-quantized MLP inference, hand-written.
 *
 * Why not TFLite Micro: the network is three dense layers. The interpreter,
 * its op resolver and its tensor arena cost more flash and RAM than the whole
 * rest of the firmware, to run an operator set I can write in fifty lines.
 * Writing it out also means the quantization scheme is mine end to end, so
 * the Python trainer and this C kernel can be proved bit-for-bit identical
 * (tests/test_model_parity.c does exactly that against vectors emitted by
 * ml/train.py).
 *
 * Scheme: symmetric per-tensor int8 weights, int32 accumulate, per-layer
 * output requantization, ReLU between layers, argmax on the final logits.
 * Inputs are standardised with the mean/scale learned at training time, then
 * quantized to int8 with a fixed input scale.
 */
#ifndef AERIS_MODEL_H
#define AERIS_MODEL_H

#include <stdbool.h>
#include <stdint.h>
#include "aeris/features.h"

/* Generated by ml/export_c.py. Defines AERIS_MODEL_* dims, the layer arrays,
 * the feature standardisation constants and AERIS_N_CLASSES. */
#include "aeris/model_params.h"

typedef struct {
    int      argmax;
    float    prob[AERIS_N_CLASSES];   /* softmax of the dequantized logits */
    float    logit[AERIS_N_CLASSES];
    uint32_t inference_us;            /* filled by the caller's timer      */
} aeris_infer_t;

/* Standardise + quantize features into q[AERIS_N_FEATURES]. Split out so the
 * parity test can check quantization independently of the matmuls. */
void aeris_model_quantize_input(const float *features, int8_t *q);

/* Run the network. features must hold AERIS_N_FEATURES values. */
void aeris_model_infer(const float *features, aeris_infer_t *out);

/* Total parameter bytes, for the /api/status report. */
uint32_t aeris_model_size_bytes(void);

const char *aeris_class_name(int cls);

#endif /* AERIS_MODEL_H */
